server:
  port: 8092

spring:
  application:
    name: theme
  datasource:
    url: 'jdbc:h2:mem:formationdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

