server:
  port: 8888

spring:
  application:
    name: gatewayserver

  cloud:
    config:
      enabled: false     # No config server
    discovery:
      enabled: true      # Enable Eureka discovery

    gateway:
      routes:
        - id: r1
          uri: lb://theme
          predicates:
            - Path= /api/themes/**
        - id: r2
          uri: lb://formation
          predicates:
           - Path= /api/formations/**
        # discovery:
          #locator:
          # enabled: false  # Automatically map Eureka services to routes
          #lowerCaseServiceId: true


  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'

management:
  endpoints:
    web:
      exposure:
        include: '*'     # Expose actuator endpoints

  endpoint:
    gateway:
      access: unrestricted

eureka:
  instance:
    prefer-ip-address: true
