server:
  port: 8092

spring:
  application:
    name: formation
  datasource:
    url: 'jdbc:h2:mem:formationdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  eureka:
    client:
    service-url:
    defaultZone: 'http://localhost:8761/eureka/'

management:
  endpoints:
    web:
      exposure:
        include: '*'

